import React, { useState, useEffect, useMemo } from 'react';
import { Transaction, TransactionType } from '../types';
import { getTransactions, saveTransaction, updateTransaction, deleteTransaction, logoutUser } from '../services/storageService';
import { LogOut, Plus, Trash2, Wallet, Pencil, History, Home, Download, Loader2 } from 'lucide-react';

interface DashboardProps {
  currentUser: string;
  onLogout: () => void;
}

const Dashboard: React.FC<DashboardProps> = ({ currentUser, onLogout }) => {
  // Helper to get local date string YYYY-MM-DD
  const getLocalDate = () => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  // Helper to get local month string YYYY-MM
  const getLocalMonth = () => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    return `${year}-${month}`;
  };

  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [amount, setAmount] = useState('');
  const [label, setLabel] = useState('');
  const [type, setType] = useState<TransactionType>(TransactionType.EXPENSE);
  const currentMonth = getLocalMonth();
  const [filterDate, setFilterDate] = useState(currentMonth); // YYYY-MM
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentUser]);

  const loadData = async () => {
    setIsLoading(true);
    const data = await getTransactions();
    // Sort Ascending: Oldest date/time first (Top), Newest last (Bottom)
    setTransactions(data.sort((a, b) => {
      const dateDiff = new Date(a.date).getTime() - new Date(b.date).getTime();
      if (dateDiff === 0 && a.created_at && b.created_at) {
         return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
      }
      return dateDiff;
    }));
    setIsLoading(false);
  };

  const handleSaveTransaction = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!amount || !label) return;
    setIsSaving(true);

    if (editingId) {
      // Update existing
      const original = transactions.find(t => t.id === editingId);
      const updatedTransaction: Transaction = {
        id: editingId,
        amount: parseFloat(amount),
        label,
        date: original ? original.date : getLocalDate(),
        type,
      };

      const success = await updateTransaction(updatedTransaction);
      if (success) {
        setTransactions(prev => {
          const updated = prev.map(t => t.id === editingId ? updatedTransaction : t);
          return updated.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
        });
      }
    } else {
      // Create new
      const newTransactionPayload: Transaction = {
        id: '', // ID is generated by Supabase
        amount: parseFloat(amount),
        label,
        date: getLocalDate(), 
        type,
      };

      const savedData = await saveTransaction(newTransactionPayload);
      if (savedData) {
        setTransactions(prev => {
          const newList = [...prev, savedData];
          return newList.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
        });
      }
    }
    
    setIsSaving(false);
    resetForm();
  };

  const handleEdit = (t: Transaction) => {
    setEditingId(t.id);
    setAmount(t.amount.toString());
    setLabel(t.label);
    setType(t.type);
    setShowForm(true);
  };

  const resetForm = () => {
    setAmount('');
    setLabel('');
    setEditingId(null);
    setShowForm(false);
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('ဖျက်ရန် သေချာပါသလား?')) {
      const success = await deleteTransaction(id);
      if (success) {
        setTransactions(prev => prev.filter(t => t.id !== id));
      }
    }
  };

  const handleLogout = async () => {
    await logoutUser();
    onLogout();
  }

  const handleExportCSV = () => {
    if (transactions.length === 0) return;
    
    // CSV Header
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Date,Label,Type,Amount\n";

    // CSV Rows
    transactions.forEach(t => {
      const row = `${t.date},${t.label},${t.type},${t.amount}`;
      csvContent += row + "\n";
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `money_tracker_${currentUser}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Current Month Transactions
  const filteredTransactions = useMemo(() => {
    return transactions.filter(t => t.date.startsWith(filterDate));
  }, [transactions, filterDate]);

  // Monthly Stats (For Income/Expense Cards)
  const monthlyStats = useMemo(() => {
    const income = filteredTransactions
      .filter(t => t.type === TransactionType.INCOME)
      .reduce((acc, curr) => acc + curr.amount, 0);
    const expense = filteredTransactions
      .filter(t => t.type === TransactionType.EXPENSE)
      .reduce((acc, curr) => acc + curr.amount, 0);
    return { income, expense, net: income - expense };
  }, [filteredTransactions]);

  // History Summary (Group by month, exclude current filterDate)
  const historySummaries = useMemo(() => {
    const summaries: Record<string, { income: number, expense: number, net: number }> = {};
    transactions.forEach(t => {
      const monthKey = t.date.slice(0, 7); // YYYY-MM
      if (monthKey === filterDate) return; // Exclude current view

      if (!summaries[monthKey]) {
        summaries[monthKey] = { income: 0, expense: 0, net: 0 };
      }
      if (t.type === TransactionType.INCOME) {
        summaries[monthKey].income += t.amount;
        summaries[monthKey].net += t.amount;
      } else {
        summaries[monthKey].expense += t.amount;
        summaries[monthKey].net -= t.amount;
      }
    });
    // Sort descending (Newest months first) and take top 12
    return Object.entries(summaries)
      .sort((a, b) => b[0].localeCompare(a[0]))
      .slice(0, 12);
  }, [transactions, filterDate]);

  const formatDateDisplay = (dateStr: string) => {
    // Convert YYYY-MM-DD to DD/MM/YYYY
    if (!dateStr) return '';
    const parts = dateStr.split('-');
    if (parts.length === 3) {
      return `${parts[2]}/${parts[1]}/${parts[0]}`;
    }
    return dateStr;
  };

  const getBurmeseMonthName = (dateStr: string) => {
    const [year, month] = dateStr.split('-');
    const monthIndex = parseInt(month) - 1;
    const months = [
      "ဇန်နဝါရီ", "ဖေဖော်ဝါရီ", "မတ်", "ဧပြီ", "မေ", "ဇွန်", 
      "ဇူလိုင်", "သြဂုတ်", "စက်တင်ဘာ", "အောက်တိုဘာ", "နိုဝင်ဘာ", "ဒီဇင်ဘာ"
    ];
    return `${year} ${months[monthIndex]}လ`;
  };

  const isCurrentMonth = filterDate === currentMonth;

  if (isLoading && transactions.length === 0) {
    return (
        <div className="min-h-screen bg-dark-bg flex items-center justify-center text-emerald-500">
            <Loader2 className="animate-spin" size={48} />
        </div>
    )
  }

  return (
    <div className="min-h-screen bg-dark-bg pb-24 text-dark-text">
      {/* Header */}
      <header className="bg-dark-card shadow-md sticky top-0 z-20 border-b border-dark-border">
        <div className="max-w-4xl mx-auto px-4 py-4 flex justify-between items-center">
          <div>
            <h1 className="text-xl font-bold text-white">ငွေစာရင်း</h1>
            <p className="text-xs text-dark-muted">အသုံးပြုသူ: {currentUser}</p>
          </div>
          <div className="flex gap-2">
            <button 
                onClick={handleExportCSV} 
                className="text-dark-muted hover:text-emerald-400 transition text-xs border border-dark-border px-2 py-1 rounded flex items-center gap-1"
                title="CSV ဒေါင်းလုဒ်လုပ်ရန်"
            >
                <Download size={14} /> Export
            </button>
            <button onClick={handleLogout} className="text-dark-muted hover:text-red-500 transition text-xs border border-dark-border px-2 py-1 rounded flex items-center gap-1">
                <LogOut size={14} /> ထွက်မည်
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-6 space-y-6">
        
        {/* Transaction Table */}
        <div className="bg-dark-card rounded-xl shadow-sm border border-dark-border overflow-hidden">
          <div className="p-4 border-b border-dark-border bg-slate-800/50">
            <div className="flex justify-between items-center mb-2">
              <h3 className="font-bold text-gray-200">
                {getBurmeseMonthName(filterDate)} ငွေစာရင်း
              </h3>
              <span className="text-xs text-dark-muted bg-slate-700 px-2 py-1 rounded border border-dark-border">{filteredTransactions.length} ခု</span>
            </div>
            
            {/* Monthly Stats Header */}
            <div className="flex gap-4 text-xs sm:text-sm bg-slate-900/50 p-2 rounded-lg justify-around">
               <div className="flex flex-col items-center">
                 <span className="text-dark-muted text-[10px]">ဝင်ငွေ</span>
                 <span className="text-emerald-400 font-bold">+{monthlyStats.income.toLocaleString()}</span>
               </div>
               <div className="w-px bg-dark-border"></div>
               <div className="flex flex-col items-center">
                 <span className="text-dark-muted text-[10px]">ထွက်ငွေ</span>
                 <span className="text-red-400 font-bold">-{monthlyStats.expense.toLocaleString()}</span>
               </div>
               <div className="w-px bg-dark-border"></div>
               <div className="flex flex-col items-center">
                 <span className="text-dark-muted text-[10px]">လလက်ကျန်</span>
                 <span className={`${monthlyStats.net >= 0 ? 'text-emerald-400' : 'text-red-400'} font-bold`}>
                    {monthlyStats.net >= 0 ? '+' : ''}{monthlyStats.net.toLocaleString()}
                 </span>
               </div>
            </div>
          </div>
          
          <div className="overflow-x-auto max-h-[500px] overflow-y-auto custom-scrollbar">
            <table className="w-full text-left border-collapse">
              <thead className="bg-slate-800 sticky top-0 z-10 shadow-sm text-dark-muted">
                <tr>
                  <th className="px-6 py-3 text-xs font-bold uppercase tracking-wider whitespace-nowrap">ရက်စွဲ</th>
                  <th className="px-6 py-3 text-xs font-bold uppercase tracking-wider whitespace-nowrap">အကြောင်းအရာ</th>
                  <th className="px-6 py-3 text-xs font-bold uppercase tracking-wider whitespace-nowrap">အမျိုးအစား</th>
                  <th className="px-6 py-3 text-xs font-bold uppercase tracking-wider text-right whitespace-nowrap">ပမာဏ</th>
                  <th className="px-6 py-3 text-xs font-bold uppercase tracking-wider text-center whitespace-nowrap">လုပ်ဆောင်ချက်</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-dark-border bg-dark-card">
                {filteredTransactions.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-6 py-10 text-center text-dark-muted">
                      <div className="flex flex-col items-center justify-center">
                        <Wallet className="mb-2 opacity-50" size={32} />
                        <p>စာရင်းမရှိသေးပါ။</p>
                      </div>
                    </td>
                  </tr>
                ) : (
                  filteredTransactions.map((t) => (
                    <tr key={t.id} className="hover:bg-slate-800/80 transition duration-150 group">
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-dark-muted font-mono">
                        {formatDateDisplay(t.date)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-200">{t.label}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <span className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${
                          t.type === TransactionType.INCOME 
                            ? 'bg-emerald-900/50 text-emerald-400 border border-emerald-800' 
                            : 'bg-red-900/50 text-red-400 border border-red-800'
                        }`}>
                          {t.type === TransactionType.INCOME ? 'ဝင်ငွေ' : 'ထွက်ငွေ'}
                        </span>
                      </td>
                      <td className={`px-6 py-4 whitespace-nowrap text-sm text-right font-bold ${
                         t.type === TransactionType.INCOME ? 'text-emerald-400' : 'text-red-400'
                      }`}>
                        {t.type === TransactionType.INCOME ? '+' : '-'}{t.amount.toLocaleString()} ကျပ်
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-center">
                        <div className="flex justify-center gap-3 opacity-0 group-hover:opacity-100 transition-opacity">
                          <button 
                            onClick={() => handleEdit(t)} 
                            className="text-blue-400 hover:text-blue-300 p-1 hover:bg-slate-700 rounded-full transition" 
                            title="ပြင်ဆင်ရန်"
                          >
                            <Pencil size={16} />
                          </button>
                          <button 
                            onClick={() => handleDelete(t.id)} 
                            className="text-red-400 hover:text-red-300 p-1 hover:bg-slate-700 rounded-full transition" 
                            title="ဖျက်ရန်"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Previous Months History */}
        {historySummaries.length > 0 && (
          <div className="bg-dark-card rounded-xl shadow-sm border border-dark-border overflow-hidden">
             <div className="p-4 border-b border-dark-border bg-slate-800/50">
                <h3 className="font-bold text-gray-200 flex items-center gap-2">
                  <History size={18} className="text-dark-muted" />
                  လဟောင်း စာရင်းများ (နောက်ဆုံး ၁၂ လ)
                </h3>
             </div>
             <div className="divide-y divide-dark-border">
               {historySummaries.map(([monthKey, stats]) => (
                 <div 
                   key={monthKey} 
                   onClick={() => {
                     setFilterDate(monthKey);
                     window.scrollTo({ top: 0, behavior: 'smooth' });
                   }}
                   className="p-4 flex flex-col sm:flex-row justify-between items-center hover:bg-slate-800/80 transition cursor-pointer group"
                 >
                    <div className="font-medium text-gray-300 mb-2 sm:mb-0 group-hover:text-primary transition-colors">
                      {getBurmeseMonthName(monthKey)}
                    </div>
                    <div className="flex gap-4 text-xs sm:text-sm">
                      <div className="text-emerald-400">
                        <span className="text-dark-muted text-xs mr-1">ဝင်:</span>
                        +{stats.income.toLocaleString()}
                      </div>
                      <div className="text-red-400">
                        <span className="text-dark-muted text-xs mr-1">ထွက်:</span>
                        -{stats.expense.toLocaleString()}
                      </div>
                      <div className={`font-bold ${stats.net >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                         <span className="text-dark-muted text-xs mr-1">ကျန်:</span>
                         {stats.net >= 0 ? '+' : ''}{stats.net.toLocaleString()} ကျပ်
                      </div>
                    </div>
                 </div>
               ))}
             </div>
          </div>
        )}

        {/* Month Filter moved to bottom */}
        <div className="flex items-center justify-between bg-dark-card p-3 rounded-xl shadow-sm border border-dark-border">
          <label className="text-dark-muted font-medium">လအလိုက် ကြည့်ရန်:</label>
          <input 
            type="month" 
            value={filterDate}
            onChange={(e) => setFilterDate(e.target.value)}
            className="bg-slate-700 border border-dark-border rounded-lg px-3 py-1 text-white focus:outline-none focus:border-primary appearance-none"
            style={{ colorScheme: 'dark' }}
          />
        </div>

      </main>

      {/* Floating Action Button (Home or Plus) */}
      {isCurrentMonth ? (
        <button
          onClick={() => {
            resetForm();
            setShowForm(true);
          }}
          className="fixed bottom-6 right-6 bg-primary hover:bg-emerald-600 text-slate-900 p-4 rounded-full shadow-lg transition-all transform hover:scale-105 z-20 border-2 border-slate-900"
          title="စာရင်းသစ်ထည့်မည်"
        >
          <Plus size={28} />
        </button>
      ) : (
        <button
          onClick={() => setFilterDate(currentMonth)}
          className="fixed bottom-6 right-6 bg-slate-700 hover:bg-slate-600 text-white p-4 rounded-full shadow-lg transition-all transform hover:scale-105 z-20 border-2 border-slate-500"
          title="လက်ရှိလသို့ပြန်သွားရန်"
        >
          <Home size={28} />
        </button>
      )}

      {/* Add/Edit Transaction Modal */}
      {showForm && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center p-4 z-50 animate-fade-in backdrop-blur-sm">
          <div className="bg-dark-card rounded-2xl w-full max-w-sm p-6 shadow-2xl transform transition-all scale-100 border border-dark-border">
            <h2 className="text-xl font-bold mb-4 text-white">
              {editingId ? 'စာရင်း ပြင်ဆင်ရန်' : 'စာရင်းသစ် ထည့်မည်'}
            </h2>
            <form onSubmit={handleSaveTransaction} className="space-y-4">
              
              {/* Type Switcher */}
              <div className="flex bg-slate-700 p-1 rounded-lg">
                <button
                  type="button"
                  onClick={() => setType(TransactionType.INCOME)}
                  className={`flex-1 py-2 rounded-md text-sm font-medium transition-all ${type === TransactionType.INCOME ? 'bg-dark-card text-emerald-400 shadow-sm' : 'text-gray-400 hover:text-gray-200'}`}
                >
                  ငွေဝင်
                </button>
                <button
                  type="button"
                  onClick={() => setType(TransactionType.EXPENSE)}
                  className={`flex-1 py-2 rounded-md text-sm font-medium transition-all ${type === TransactionType.EXPENSE ? 'bg-dark-card text-red-400 shadow-sm' : 'text-gray-400 hover:text-gray-200'}`}
                >
                  ငွေထွက်
                </button>
              </div>

              <div>
                <label className="block text-sm font-medium text-dark-muted mb-1">ပမာဏ (ကျပ်)</label>
                <input
                  type="number"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  className="w-full px-4 py-2 bg-slate-700 border border-dark-border text-white rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent outline-none"
                  placeholder="0"
                  required
                  autoFocus
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-dark-muted mb-1">အကြောင်းအရာ</label>
                <input
                  type="text"
                  value={label}
                  onChange={(e) => setLabel(e.target.value)}
                  className="w-full px-4 py-2 bg-slate-700 border border-dark-border text-white rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent outline-none"
                  placeholder="ဥပမာ - ဈေးဖိုး"
                  required
                />
              </div>

              <div className="pt-2 flex gap-3">
                <button
                  type="button"
                  onClick={resetForm}
                  className="flex-1 px-4 py-2 border border-dark-border text-gray-300 rounded-lg hover:bg-slate-700 transition"
                  disabled={isSaving}
                >
                  မလုပ်တော့ပါ
                </button>
                <button
                  type="submit"
                  disabled={isSaving}
                  className={`flex-1 px-4 py-2 bg-primary text-slate-900 font-bold rounded-lg hover:bg-emerald-600 transition ${isSaving ? 'opacity-50' : ''}`}
                >
                  {isSaving ? 'သိမ်းနေသည်...' : (editingId ? 'ပြင်ဆင်မည်' : 'သိမ်းမည်')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;